include:
  - arr/docker-compose.yml
  - backups/docker-compose.yml
  # - forgejo/docker-compose.yml
  - freshrss/docker-compose.yml
  - glance/docker-compose.yml
  - immich/docker-compose.yml
  - media/docker-compose.yml
  - minecraft/docker-compose.yml
  - network/docker-compose.yml
  - paperless/docker-compose.yml
  - productivity/docker-compose.yml
  # - romm/docker-compose.yml
  # - vaultwarden/docker-compose.yml
  # - wger/docker-compose.yml