include:
  - arr/docker-compose.yml
  - glance/docker-compose.yml
  - immich/docker-compose.yml
  - media/docker-compose.yml
  - network/docker-compose.yml
  - productivity/docker-compose.yml
  - romm/docker-compose.yml
  # - wger/docker-compose.yml
  - docker-compose.vaultwarden.yml