networks:
  proxy-public:
    external: true

services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    labels:
      glance.name: Vaultwarden
      glance.icon: si:vaultwarden
      glance.url: https://vault.richard-hughes.dev
      glance.category: Productivity
      glance.description: Passwords

      # https://github.com/dani-garcia/vaultwarden/wiki/Proxy-examples
      # global init + middleware definition
      traefik.enable: "true"
      traefik.docker.network: "proxy-public"
      traefik.http.middlewares.redirect-https.redirectScheme.scheme: "https"
      traefik.http.middlewares.redirect-https.redirectScheme.permanent: "true"

      # router: vaultwarden-https for secure traffic
      traefik.http.routers.vaultwarden-https.rule: Host(`vault.richard-hughes.dev`)
      traefik.http.routers.vaultwarden-https.entrypoints: websecure
      traefik.http.routers.vaultwarden-https.tls: "true"
      traefik.http.routers.vaultwarden-https.service: vaultwarden

      # router: vaultwarden-http to redirect to https
      traefik.http.routers.vaultwarden-http.rule: Host(`vault.richard-hughes.dev`)
      traefik.http.routers.vaultwarden-http.entrypoints: web
      traefik.http.routers.vaultwarden-http.middlewares: redirect-https
      traefik.http.routers.vaultwarden-http.service: vaultwarden

      # service: vaultwarden as the actual backend destination
      traefik.http.services.vaultwarden.loadbalancer.server.port: "80"
    restart: unless-stopped
    environment:
      SIGNUPS_ALLOWED: ${SIGNUPS} # Deactivate this with "false" after you have created your account so that no strangers can register
    volumes:
      - ${DATA}/Vaultwarden:/data # the path before the : can be changed
    networks:
      - proxy-public
