networks:
  proxy-public:
    external: true

services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: "1000:1000"
    volumes:
      - ${DATA}/jellyfin/config:/config
      - ${DATA}/jellyfin/cache:/cache
      - ${FILMS}:/films
      - ${MUSIC}:/music
      - ${SHOWS}:/shows
    restart: unless-stopped
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
    group_add:
      - ${RENDER_GID}
    networks:
      - proxy-public
    labels:
      glance.name: Jellyfin
      glance.icon: si:jellyfin
      glance.description: Films & Shows
      glance.category: Media
      glance.url: https://jellyfin.${DOMAIN}/
      traefik.enable: "true"
      traefik.docker.network: "proxy-public"
      
      traefik.http.routers.jf.rule: Host(`jellyfin.${DOMAIN}`)
      traefik.http.routers.jf.entrypoints: websecure
      traefik.http.routers.jf.tls: true
      traefik.http.services.jf.loadbalancer.server.port: "8096"
    
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    volumes:
      - ${AUDIOBOOKS}:/audiobooks
      - ${DATA}/audiobookshelf/config:/config
      - ${DATA}/audiobookshelf/metadata:/metadata
    restart: unless-stopped
    networks:
      - proxy-public
    labels:
      glance.name: Audiobookshelf
      glance.icon: si:audiobookshelf
      glance.description: Audiobooks & eBooks
      glance.category: Media
      glance.url: https://abs.${DOMAIN}
      
      traefik.enable: "true"
      traefik.docker.network: "proxy-public"
      
      traefik.http.routers.abs.rule: Host(`abs.richard-hughes.dev`)
      traefik.http.routers.abs.entrypoints: websecure
      traefik.http.routers.abs.tls: true
      traefik.http.services.abs.loadbalancer.server.port: "80"