networks:
  proxy-public:
    external: true

services:
  traefik:
    image: traefik:v3.7
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    # Since this is Tailscale-only, your public router ports 80/443 remain closed.
    # Traefik will listen internally on your host machine (and thus your Tailscale IP).
    ports:
      - "80:80"
      - "443:443"
    environment:
      - CF_DNS_API_TOKEN=${CLOUDFLARE_DNS_KEY}
      - CF_ACCOUNT_ID=4a63dfc7eae89fd58536432be50f5615
      - ACME_EMAIL=${ACME_EMAIL}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt # Certificate storage location
    networks:
      - proxy-public
    labels:
      glance.name: Traefik
      glance.icon: si:traefikproxy
      glance.description: Reverse Proxy
      glance.category: System
      glance.url: https://traefik.${DOMAIN}/dashboard/

      traefik.enable: "true"
      traefik.docker.network: "proxy-public"

      # Create a local middleware on Traefik called "global-hardening"
      traefik.http.middlewares.global-hardening.headers.customResponseHeaders.X-Robots-Tag: "noindex,nofollow,nosnippet"
      traefik.http.middlewares.global-hardening.headers.frameDeny: "true"
      traefik.http.middlewares.global-hardening.headers.contentTypeNosniff: "true"
      traefik.http.middlewares.global-hardening.headers.stsSeconds: "315360000"
      traefik.http.middlewares.global-hardening.headers.stsIncludeSubdomains: "true"
      traefik.http.middlewares.global-hardening.headers.stsPreload: "true"

      # Expose dashboard
      traefik.http.routers.dashboard.rule: Host(`traefik.${DOMAIN}`)
      traefik.http.routers.dashboard.service: api@internal
      traefik.http.routers.dashboard.entrypoints: websecure
      traefik.http.routers.dashboard.tls: true
      # Fetches TLS certification explictly, so other contaienrs can default to them
      traefik.http.routers.dashboard.tls.certresolver: cloudflare-resolver
      traefik.http.routers.dashboard.tls.domains[0].main: ${DOMAIN}
      traefik.http.routers.dashboard.tls.domains[0].sans: "*.${DOMAIN}"
      # Optional: Add basic auth middleware for security
      # traefik.http.routers.dashboard.middlewares: auth

    command:
      - "--global.checknewversion=false"
      - "--global.sendanonymoususage=false"
      - "--log.level=DEBUG"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=proxy-public"

      # 1. HTTP/HTTPS Entrypoint & HTTPS Redirect
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"

      # 2. Inject hardening middleware globally
      - "--entrypoints.websecure.http.middlewares=global-hardening@docker"

      # 3. Set Cloudflare as the DNS resolver & Let's Encrypt DNS Challenge
      - "--entrypoints.websecure.http.tls.certresolver=cloudflare-resolver"
      - "--entrypoints.websecure.http.tls.domains[0].main=richard-hughes.dev"
      - "--entrypoints.websecure.http.tls.domains[0].sans=*.richard-hughes.dev"
      - "--certificatesresolvers.cloudflare-resolver.acme.dnschallenge=true"
      - "--certificatesresolvers.cloudflare-resolver.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.cloudflare-resolver.acme.dnschallenge.resolvers=1.1.1.1:53"
      - "--certificatesresolvers.cloudflare-resolver.acme.dnschallenge.resolvers=1.0.0.1:53"
      - "--certificatesresolvers.cloudflare-resolver.acme.email=${ACME_EMAIL}"
      - "--certificatesresolvers.cloudflare-resolver.acme.storage=/letsencrypt/acme.json"

      # 4. Dashboard
      - "--api.dashboard=true"
      - "--api.insecure=false"
      - "--api.disabledashboardad=true"

  adguardhome:
    image: adguard/adguardhome:latest
    container_name: adguardhome
    restart: unless-stopped
    command: [ 
      "--web-addr", "0.0.0.0:8060",
      "--config", "/opt/adguardhome/conf/AdGuardHome.yaml",
      "--work-dir", "/opt/adguardhome/work"
    ]
    labels:
      glance.name: AdGuard Home
      glance.icon: si:adguard
      glance.description: Adblock & DNS
      glance.category: System
      glance.url: http://${URL}:3000
    network_mode: host
    volumes:
      - ./work:/opt/adguardhome/work:rw
      - ./conf:/opt/adguardhome/conf:rw

  tailscale:
    image: tailscale/tailscale:latest
    container_name: tailscale
    labels:
      glance.name: Tailscale
      glance.icon: si:tailscale
      glance.description: VPN
      glance.category: System
      glance.url: https://login.tailscale.com/admin/machines
    hostname: barry
    network_mode: "host"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_EXTRA_ARGS=--advertise-tags=tag:server  # Optional: for ACLs
    volumes:
      - ${DATA}/tailscale:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    # The official image's entrypoint handles login if TS_AUTHKEY is present
    restart: unless-stopped
    
  samba:
    image: ghcr.io/servercontainers/samba:smbd-wsdd2-latest
    container_name: samba
    labels:
      glance.name: Samba
      glance.icon: si:protondrive
      glance.description: Network Storage
      glance.category: System
      glance.url: smb://${URL}/Media
    network_mode: host
    environment:
      SAMBA_GLOBAL_CONFIG_workgroup: WORKGROUP
      ACCOUNT_richard: ${SAMBA_PASSWORD}
      UID_richard: ${PUID}
      GROUPS_richard: ${PGID}

      ACCOUNT_person: ${SAMBA_PASSWORD}
      UID_person: ${PUID}
      GROUPS_person: ${PGID}

      SAMBA_VOLUME_CONFIG_media: >
        [Media];
        path=/shares/media;
        guest ok = no;
        read only = no;
        browseable = yes;
        writable = yes;
        force user = richard;
        valid users = richard, person
    volumes:
      - ${MEDIA}:/shares/media
    restart: unless-stopped
