networks:
  forgejo:
    external: false

services:
  actual_budget:
    labels:
      glance.name: Actual Budget
      glance.icon: si:actualbudget
      glance.url: http://${URL}:5006
      glance.description: Finances
      glance.category: Productivity
      glance.id: actualbudget
    image: docker.io/actualbudget/actual-server:latest
    ports:
      - '5006:5006'
    # environment:
      # Uncomment any of the lines below to set configuration options.
      # - ACTUAL_HTTPS_KEY=/data/selfhost.key
      # - ACTUAL_HTTPS_CERT=/data/selfhost.crt
      # - ACTUAL_PORT=5006
      # - ACTUAL_UPLOAD_FILE_SYNC_SIZE_LIMIT_MB=20
      # - ACTUAL_UPLOAD_SYNC_ENCRYPTED_FILE_SYNC_SIZE_LIMIT_MB=50
      # - ACTUAL_UPLOAD_FILE_SIZE_LIMIT_MB=20
      # See all options and more details at https://actualbudget.org/docs/config/
      # !! If you are not using any of these options, remove the 'environment:' tag entirely.
    volumes:
      # Change './actual-data' below to the path to the folder you want Actual to store its data in on your server.
      # '/data' is the path Actual will look for its files in by default, so leave that as-is.
      - ${DATA}/actual_budget:/data
    healthcheck:
      # Enable health check for the instance
      test: ['CMD-SHELL', 'node scripts/health-check.js']
      # health check using self signed certs
      # test: ['CMD-SHELL', 'NODE_EXTRA_CA_CERTS=/data/selfhost.crt node scripts/health-check.js']
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 20s
    restart: unless-stopped

  forgejo:
    labels:
        glance.name: Forgejo
        glance.icon: si:forgejo
        glance.url: http://${URL}:3001
        glance.description: Git Repositories
        glance.category: Productivity
        glance.id: forgejo
    image: codeberg.org/forgejo/forgejo:15
    environment:
      - USER_UID=${PUID}
      - USER_GID=${PGID}
    restart: always
    networks:
      - forgejo
    volumes:
      - ${DATA}/forgejo:/data
      - /etc/localtime:/etc/localtime:ro
    ports:
      - '3001:3000'
      - '222:22'

  tandoor:
    labels:
      glance.name: Tandoor
      glance.icon: si:mealie
      glance.url: http://${URL}:9926
      glance.description: Recipes
      glance.category: Productivity
      glance.id: tandoor
    restart: always
    image: vabene1111/recipes:latest
    ports:
      - 9926:80
    volumes:
      - ${DATA}/tandoor_data:/opt/recipes/data
      - ${DATA}/tandoor_static:/opt/recipes/staticfiles
      - ${DATA}/tandoor_media:/opt/recipes/mediafiles
    environment:
      - SECRET_KEY=your_secure_random_string_here
      - ALLOWED_HOSTS=*
      # Tell Tandoor to use SQLite instead of Postgres
      - DB_ENGINE=django.db.backends.sqlite3

  # mealie:
  #   image: ghcr.io/mealie-recipes/mealie:v3.9.2 # 
  #   container_name: mealie
  #   restart: always
  #   labels:
  #     glance.name: Mealie
  #     glance.icon: si:mealie
  #     glance.url: http://${URL}:9925
  #     glance.description: Recipes
  #     glance.category: Productivity
  #     glance.id: mealie
  #   ports:
  #       - "9925:9000" # 
  #   deploy:
  #     resources:
  #       limits:
  #         memory: 1000M # 
  #   volumes:
  #     - ${DATA}/mealie:/app/data/
  #   environment:
  #     # Set Backend ENV Variables Here
  #     ALLOW_SIGNUP: ${SIGNUPS}
  #     PUID: ${PUID}
  #     PGID: ${PGID}
  #     TZ: Europe/London

  syncthing:
    image: syncthing/syncthing
    container_name: syncthing
    labels:
      glance.name: Syncthing
      glance.icon: si:syncthing
      glance.url: http://${URL}:8384
      glance.description: File Sync
      glance.category: Productivity
      glance.id: syncthing
    # hostname: my-syncthing
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      # - STGUIADDRESS=
    volumes:
      - ${DATA}/syncthing:/var/syncthing/config
      - ${MEDIA}/Sync:/var/syncthing
    network_mode: host
    restart: unless-stopped
    healthcheck:
      test: curl -fkLsS -m 2 127.0.0.1:8384/rest/noauth/health | grep -o --color=never OK || exit 1
      interval: 1m
      timeout: 10s
      retries: 3

  vikunja:
    image: vikunja/vikunja
    labels:
      glance.name: Vikunja
      glance.icon: si:vikunja
      glance.url: http://${URL}:3456
      glance.description: Todo Lists
      glance.category: Productivity
      glance.id: vikunja
    environment:
      VIKUNJA_SERVICE_JWTSECRET: ${VIKUNJA_SECRET}
      VIKUNJA_SERVICE_PUBLICURL: ${PREFIX}${URL}:3456
      VIKUNJA_DATABASE_TYPE: sqlite
    ports:
      - 3456:3456
    volumes:
      - ${DATA}/vikunja/files:/app/vikunja/files
      - ${DATA}/vikunja/db:/db
    restart: unless-stopped