networks:
  forgejo:
    external: false
  proxy-public:
    external: true

services:
  actual_budget:
    image: docker.io/actualbudget/actual-server:latest
    # environment:
      # See all options and more details at https://actualbudget.org/docs/config/
    volumes:
      - ${DATA}/actual_budget:/data
    healthcheck:
      test: ['CMD-SHELL', 'node scripts/health-check.js']
      # health check using self signed certs
      # test: ['CMD-SHELL', 'NODE_EXTRA_CA_CERTS=/data/selfhost.crt node scripts/health-check.js']
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 20s
    restart: unless-stopped
    networks:
      - proxy-public
    labels:
      glance.name: Actual Budget
      glance.icon: si:actualbudget
      glance.url: https://actual.${DOMAIN}
      glance.description: Finances
      glance.category: Productivity
      glance.id: actualbudget

      traefik.enable: true
      traefik.docker.network: "proxy-public"
      
      traefik.http.routers.actual.rule: Host(`actual.${DOMAIN}`)
      traefik.http.routers.actual.entrypoints: websecure
      traefik.http.routers.actual.tls: true
      traefik.http.services.actual.loadbalancer.server.port: "5006"

  forgejo:
    image: codeberg.org/forgejo/forgejo:15
    environment:
      - USER_UID=${PUID}
      - USER_GID=${PGID}
    restart: always
    networks:
      - proxy-public
      - forgejo
    volumes:
      - ${DATA}/forgejo:/data
      - /etc/localtime:/etc/localtime:ro
    ports:
      - '222:22'
    labels:
      glance.name: Forgejo
      glance.icon: si:forgejo
      glance.url: https://forgejo.${DOMAIN}
      glance.description: Git Repositories
      glance.category: Productivity
      glance.id: forgejo

      traefik.enable: true
      traefik.docker.network: "proxy-public"
      
      traefik.http.routers.forge.rule: Host(`forgejo.${DOMAIN}`)
      traefik.http.routers.forge.entrypoints: websecure
      traefik.http.routers.forge.tls: true
      traefik.http.services.forge.loadbalancer.server.port: "3000"

  tandoor:
    restart: unless-stopped
    image: vabene1111/recipes:latest
    volumes:
      - ${DATA}/tandoor_data:/opt/recipes/data
      - ${DATA}/tandoor_static:/opt/recipes/staticfiles
      - ${DATA}/tandoor_media:/opt/recipes/mediafiles
    environment:
      - SECRET_KEY=your_secure_random_string_here
      - ALLOWED_HOSTS=*
      # Tell Tandoor to use SQLite instead of Postgres
      - DB_ENGINE=django.db.backends.sqlite3
    networks:
      - proxy-public
    labels:
      glance.name: Tandoor
      glance.icon: si:mealie
      glance.url: https://tandoor.${DOMAIN}
      glance.description: Recipes
      glance.category: Productivity
      glance.id: tandoor

      traefik.enable: true
      traefik.docker.network: "proxy-public"
      
      traefik.http.routers.tandoor.rule: Host(`tandoor.${DOMAIN}`)
      traefik.http.routers.tandoor.entrypoints: websecure
      traefik.http.routers.tandoor.tls: true
      traefik.http.services.tandoor.loadbalancer.server.port: "80"

  syncthing:
    image: syncthing/syncthing
    container_name: syncthing
    labels:
      glance.name: Syncthing
      glance.icon: si:syncthing
      glance.url: http://${URL}:8384
      glance.description: File Sync
      glance.category: Productivity
      glance.id: syncthing
    # hostname: my-syncthing
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      # - STGUIADDRESS=
    volumes:
      - ${DATA}/syncthing:/var/syncthing/config
      - ${MEDIA}/Sync:/var/syncthing
    network_mode: host
    restart: unless-stopped
    healthcheck:
      test: curl -fkLsS -m 2 127.0.0.1:8384/rest/noauth/health | grep -o --color=never OK || exit 1
      interval: 1m
      timeout: 10s
      retries: 3

  vikunja:
    image: vikunja/vikunja
    environment:
      VIKUNJA_SERVICE_JWTSECRET: ${VIKUNJA_SECRET}
      VIKUNJA_SERVICE_PUBLICURL: https://vikunja.richard-hughes.dev/
      VIKUNJA_DATABASE_TYPE: sqlite
    volumes:
      - ${DATA}/vikunja/files:/app/vikunja/files
      - ${DATA}/vikunja/db:/db
    restart: unless-stopped
    networks:
      - proxy-public
    labels:
      glance.name: Vikunja
      glance.icon: si:vikunja
      glance.url: https://vikunja.${DOMAIN}
      glance.description: Todo Lists
      glance.category: Productivity
      glance.id: vikunja

      traefik.enable: true
      traefik.docker.network: "proxy-public"
      
      traefik.http.routers.vikunja.rule: Host(`vikunja.${DOMAIN}`)
      traefik.http.routers.vikunja.entrypoints: websecure
      traefik.http.routers.vikunja.tls: true
      traefik.http.services.vikunja.loadbalancer.server.port: "3456"