services:
  mc:
    image: itzg/minecraft-server:latest
    tty: true
    stdin_open: true
    pull_policy: daily
    environment:
      EULA: "true"
      TYPE: "PAPER"
      VERSION: "26.2"
      MEMORY: "4G"
      ENABLE_WHITELIST: "true"
      ENFORCE_WHITELIST: "true"
      PLUGINS: |
        https://download.geysermc.org/v2/projects/geyser/versions/latest/builds/latest/downloads/spigot
        https://download.geysermc.org/v2/projects/floodgate/versions/latest/builds/latest/downloads/spigot
    volumes:
      - ${MEDIA}/Minecraft:/data
    networks:
      - mc-net
    labels:
      glance.id: mc
      glance.name: Minecraft
      glance.icon: auto-invert sh:minecraft-dark
      glance.url: ${PLAYIT_TUNNEL}
      glance.category: Media
      glance.description: Multiplayer Server

      docker-volume-backup.stop-during-backup: "true"

  playit:
    image: ghcr.io/playit-cloud/playit-agent:latest
    container_name: playit-agent
    restart: unless-stopped
    # environment:
      # Optional: paste your agent secret key here once generated
        # - SECRET_KEY=
    volumes:
      - ${DATA}/playit:/data
    networks:
      - mc-net
    labels:
      glance.parent: mc
      glance.name: PlayIt Agent

networks:
  mc-net:
    driver: bridge