networks:
  proxy-public:
    external: true  

services:
  freshrss:
    image: freshrss/freshrss:latest
    container_name: freshrss
    restart: unless-stopped
    logging:
      options:
        max-size: 10m
    volumes:
      - ${DATA}/freshrss/data:/var/www/FreshRSS/data
      - ${DATA}/freshrss/extensions:/var/www/FreshRSS/extensions
    environment:
      TZ: Europe/London
      # Cron job to refresh feeds at specified minutes
      CRON_MIN: '2,32'
    # Optional healthcheck
    healthcheck:
      test: ["CMD", "cli/health.php"]
      timeout: 10s
      start_period: 60s
      start_interval: 11s
      interval: 75s
      retries: 3
    networks:
    - proxy-public
    labels:
      glance.name: FreshRSS
      glance.icon: si:freshrss
      glance.description: Articles
      glance.category: Media
      glance.url: https://freshrss.${DOMAIN}/

      docker-volume-backup.stop-during-backup: "true"
      
      traefik.enable: "true"
      traefik.docker.network: "proxy-public"
      
      traefik.http.routers.freshrss.rule: Host(`freshrss.${DOMAIN}`)
      traefik.http.routers.freshrss.entrypoints: websecure
      traefik.http.routers.freshrss.tls: true
      traefik.http.services.freshrss.loadbalancer.server.port: "80"

  extension-sync:
    image: alpine/git
    restart: "no"
    volumes:
      - ${DATA}/freshrss/extensions:/extensions
      - ./extensions.sh:/extensions.sh:ro
    entrypoint: ["/bin/sh", "/extensions.sh"]