- name: Home
  # Optionally, if you only have a single page you can hide the desktop navigation for a cleaner look
  # hide-desktop-navigation: true
  columns:
    - size: small
      widgets:
        - type: clock
          hour-format: 24h
        - type: group
          widgets:
            - type: weather
              title: ${LOCATION_1}
              location: ${OPEN_METEO_LOCATION_1}
              units: metric
              hour-format: 24h          
            - type: weather
              title: ${LOCATION_2}
              location: ${OPEN_METEO_LOCATION_2}
              units: metric
              hour-format: 24h
            - type: weather
              title: ${LOCATION_3}
              location: ${OPEN_METEO_LOCATION_3}
              units: metric
              hour-format: 24h
          #taken from yahoo finance
        - type: markets
          markets:
            - symbol: SPY
              name: S&P 500
            - symbol: NQ=F
              name: Nasdaq 100
            - symbol: BTC-GBP
              name: Bitcoin

    - size: full
      widgets:
        - type: search
          search-engine: https://search.brave.com/search?q={QUERY}
          bangs:
            - title: YouTube
              shortcut: "!yt"
              url: https://www.youtube.com/results?search_query={QUERY}
        - type: docker-containers
          title: Media
          category: Media
          sock-path: tcp://glance-socket-proxy:2375
        - type: docker-containers
          running-only: true
          title: Productivity
          category: Productivity
          sock-path: tcp://glance-socket-proxy:2375
        - type: docker-containers
          running-only: true
          title: System
          category: System
          sock-path: tcp://glance-socket-proxy:2375

    - size: small
      widgets:
        - type: server-stats
          servers:
            - type: local
              name: Barry
              mountpoints:
                "/host":
                  name: Internal
                "/host/mnt/media":
                  name: Media
                "/host/mnt/backups":
                  name: Backups
                "/host/boot":
                  hide: true
        - type: dns-stats
          service: adguard
          url: http://host.docker.internal:8060
          username: ${ADGUARD_USERNAME}
          password: ${ADGUARD_PASSWORD}
        - $include: leetcode.yml
        - type: group
          widgets:
          - type: extension
            title: Restic
            url: http://restic-glance:8675/repo1
            cache: 10s # set to any time of your choice.
            allow-potentially-dangerous-html: true
          - $include: immich.yml
          - $include: abs.yml