networks:
  proxy-public:
    external: true
  miniflux-internal:

services:
  pg:
    image: postgres:18
    container_name: postgres
    labels:
      glance.parent: Miniflux
      glance.name: Database
    environment:
      - POSTGRES_USER=miniflux
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=miniflux
    volumes:
      # You may have to adjust the volume path depending on the version of Postgres
      # Postgres 18 uses /var/lib/postgresql
      # Postgres 17 and below uses /var/lib/postgresql/data
      # See https://hub.docker.com/_/postgres#pgdata
      - ${DATA}/miniflux:/var/lib/postgresql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "miniflux"]
      interval: 10s
      start_period: 30s
    networks:
      - miniflux-internal
    restart: unless-stopped

  miniflux:
    image: miniflux/miniflux:latest
    container_name: miniflux
    depends_on:
      pg:
        condition: service_healthy
    environment:
      # - DATABASE_URL=postgres://miniflux:secret@db/miniflux?sslmode=disable
      - DATABASE_URL=postgres://miniflux:secret@miniflux-db/miniflux?sslmode=disable
      - RUN_MIGRATIONS=1
      - CREATE_ADMIN=1
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=test123
    networks:
      - proxy-public
      - miniflux-internal
    labels:
      glance.name: Miniflux
      glance.icon: si:rss
      glance.description: Articles
      glance.category: Media
      glance.url: https://miniflux.${DOMAIN}/
      
      traefik.enable: "true"
      traefik.docker.network: "proxy-public"
      
      traefik.http.routers.miniflux.rule: Host(`miniflux.${DOMAIN}`)
      traefik.http.routers.miniflux.entrypoints: websecure
      traefik.http.routers.miniflux.tls: true
      traefik.http.services.miniflux.loadbalancer.server.port: "8080"